name: .NET Release Build

on:
  release:
    types: [created]

jobs:
  build:
    name: Build for ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            rid: linux-x64
          - os: macos-latest
            arch: arm64
            rid: osx-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true /p:PublishSingleFile=true /p:DebugSymbols=false /p:DebugType=None

    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        cd bin/Release/net9.0/${{ matrix.rid }}/publish
        asset_name="cpm-${{ matrix.rid }}"
        mv cpm "$asset_name"
        gh release upload ${{ github.event.release.tag_name }} "$asset_name"
